Kel 108
WojOgi/Housing_Management pull request #15
Opened 2023-10-30 05:04 UTC by WojOgi

2023-10-30 18:41 UTC, xast89 requested changes

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/api/controllers/AssignmentController.java
> +    @PutMapping(value = "/occupants/assign_occupant")
Z jakiego arytkułu brałeś informację, jak tworzyć path'y w endpointach? Bo tutaj masz taką struktue:
/occupants/assign_occupant.

Czyli ja wiem, że jestem w kontekście occupants (bo pierwszy człon), więc drugi człon nie musi mi przypominać, że assignuje occupanta :)

Czyli wystarczy /occupants/assign

Co Ty na to?

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/api/controllers/AssignmentController.java
> +    @PutMapping(value = "/occupants/move_occupant")
tutaj podobnie. Wystarczy samo 'move'

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/api/controllers/HouseController.java
>      public ResponseEntity<List<HouseResponse>> getAllHouses() {
Jak będziesz miał 500 domów to będziemy chcieli zwrócić je wszystkie? W takim przypadku należy rozważyć stronnicowanie (paginacje) - to tak na przyszłość :)

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/api/dbentities/HouseInternalEntity.java
> +    private LocalDateTime dateUpdated;
Dlaczego LocalDateTime a nie Instant?

Co do nazwy zmeinnej - nie trzeba słówka 'date'. Co myślisz o 'updatedAt / 'createdAt' ?'

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/api/dbentities/HouseInternalEntity.java
> +    public HouseInternalEntity(LocalDateTime dateCreated, String houseNumber, int maxCapacity, int currentCapacity) {
Po co tyle konsktruktorów? Widzę, że połowa nieużywana

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/HousingmanagementApplication.java
> +import org.springframework.stereotype.Component;
zbędnę

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/HousingmanagementApplication.java
> +
to też

2023-10-30 18:41 UTC, xast89 commented on src/main/java/com/example/housingmanagement/MyCommandLineRunner.java
> +public class MyCommandLineRunner implements CommandLineRunner {
To cudo docelowo zniknie - ale fajnie że poznałeś sposób, że można 'wbić się' ze swoją logiką w proces startowania aplikacji Springowej <3

2023-11-02 04:40 UTC, WojOgi commented on src/main/java/com/example/housingmanagement/api/controllers/AssignmentController.java
> +    @PutMapping(value = "/occupants/assign_occupant")
haha, z artykułu: "Wojtka wolna twórczość" Nie no, masz rację. To jeszcze będzie do przerobienia filozofia wybierania endpointó.

2023-11-02 04:42 UTC, WojOgi commented on src/main/java/com/example/housingmanagement/api/controllers/HouseController.java
>      public ResponseEntity<List<HouseResponse>> getAllHouses() {
ok - to tutaj zrobię na tej podstawie zadanko typu: implmentacja paging/sorting.

2023-11-02 04:46 UTC, WojOgi commented on src/main/java/com/example/housingmanagement/api/dbentities/HouseInternalEntity.java
> +    private LocalDateTime dateUpdated;
z tego co widzę to LocalDateTime zawiera info o strefie czasowej, Instant operuje na UTC. Są chyba plusy i minusy obu typów. To na razie zostawię LocalDateTime ale będę pamiętał że można zastąpić na Instant.

2023-11-02 04:47 UTC, WojOgi commented on src/main/java/com/example/housingmanagement/api/dbentities/HouseInternalEntity.java
> +    public HouseInternalEntity(LocalDateTime dateCreated, String houseNumber, int maxCapacity, int currentCapacity) {
good point. Się pojawiały przy dodawaniu pól - to pousuwam niepotrzebne.

2023-11-02 04:48 UTC, WojOgi commented on src/main/java/com/example/housingmanagement/HousingmanagementApplication.java
> +import org.springframework.stereotype.Component;
done

2023-11-02 05:00 UTC, merged